### ISSUE TITLE
Remove BoolOption from argparser?

### ISSUE THREAD

**Issue by Fyren** [alliedmodders/amtl#89]
BoolOption is broken because since it _can_ take true/false, so it tries to eat the next thing on the command line.  If it fails, because the next thing is just another parameter or whatever, it just leaves the option's value in the default state.  So `./cmd --bool-option positional` with a default of false means that option stays false, the same as if `--bool-option` wasn't given.

Can probably just kill it off in favor of ToggleOption/EnableOption.

**Comment by dvander** [comment]
Removed.
